/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "ball_t.h"

static int __ball_t_hash_computed;
static int64_t __ball_t_hash;
 
int64_t __ball_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __ball_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__ball_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x6241ac31f9394276LL
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __ball_t_get_hash(void)
{
    if (!__ball_t_hash_computed) {
        __ball_t_hash = __ball_t_hash_recursive(NULL);
        __ball_t_hash_computed = 1;
    }
 
    return __ball_t_hash;
}
 
int __ball_t_encode_array(void *buf, int offset, int maxlen, const ball_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].colour), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int ball_t_encode(void *buf, int offset, int maxlen, const ball_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ball_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __ball_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __ball_t_encoded_array_size(const ball_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __double_encoded_array_size(p[element].position, 2);
 
        size += __int32_t_encoded_array_size(&(p[element].colour), 1);
 
    }
    return size;
}
 
int ball_t_encoded_size(const ball_t *p)
{
    return 8 + __ball_t_encoded_array_size(p, 1);
}
 
int __ball_t_decode_array(const void *buf, int offset, int maxlen, ball_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].colour), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __ball_t_decode_array_cleanup(ball_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __double_decode_array_cleanup(p[element].position, 2);
 
        __int32_t_decode_array_cleanup(&(p[element].colour), 1);
 
    }
    return 0;
}
 
int ball_t_decode(const void *buf, int offset, int maxlen, ball_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __ball_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __ball_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int ball_t_decode_cleanup(ball_t *p)
{
    return __ball_t_decode_array_cleanup(p, 1);
}
 
int __ball_t_clone_array(const ball_t *p, ball_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __double_clone_array(p[element].position, q[element].position, 2);
 
        __int32_t_clone_array(&(p[element].colour), &(q[element].colour), 1);
 
    }
    return 0;
}
 
ball_t *ball_t_copy(const ball_t *p)
{
    ball_t *q = (ball_t*) malloc(sizeof(ball_t));
    __ball_t_clone_array(p, q, 1);
    return q;
}
 
void ball_t_destroy(ball_t *p)
{
    __ball_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int ball_t_publish(lcm_t *lc, const char *channel, const ball_t *p)
{
      int max_data_size = ball_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = ball_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _ball_t_subscription_t {
    ball_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void ball_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    ball_t p;
    memset(&p, 0, sizeof(ball_t));
    status = ball_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding ball_t!!!\n", status);
        return;
    }

    ball_t_subscription_t *h = (ball_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    ball_t_decode_cleanup (&p);
}

ball_t_subscription_t* ball_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    ball_t_handler_t f, void *userdata)
{
    ball_t_subscription_t *n = (ball_t_subscription_t*)
                       malloc(sizeof(ball_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 ball_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg ball_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int ball_t_unsubscribe(lcm_t *lcm, ball_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe ball_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

