/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "balls_t.h"

static int __balls_t_hash_computed;
static int64_t __balls_t_hash;
 
int64_t __balls_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __balls_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__balls_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x8fec9e5cb91d576dLL
         + __info_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __ball_t_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __balls_t_get_hash(void)
{
    if (!__balls_t_hash_computed) {
        __balls_t_hash = __balls_t_hash_recursive(NULL);
        __balls_t_hash_computed = 1;
    }
 
    return __balls_t_hash;
}
 
int __balls_t_encode_array(void *buf, int offset, int maxlen, const balls_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].balls_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __ball_t_encode_array(buf, offset + pos, maxlen - pos, p[element].balls, p[element].balls_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int balls_t_encode(void *buf, int offset, int maxlen, const balls_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __balls_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __balls_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __balls_t_encoded_array_size(const balls_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __info_t_encoded_array_size(&(p[element].info), 1);
 
        size += __int32_t_encoded_array_size(&(p[element].balls_size), 1);
 
        size += __ball_t_encoded_array_size(p[element].balls, p[element].balls_size);
 
    }
    return size;
}
 
int balls_t_encoded_size(const balls_t *p)
{
    return 8 + __balls_t_encoded_array_size(p, 1);
}
 
int __balls_t_decode_array(const void *buf, int offset, int maxlen, balls_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].balls_size), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        p[element].balls = (ball_t*) lcm_malloc(sizeof(ball_t) * p[element].balls_size);
        thislen = __ball_t_decode_array(buf, offset + pos, maxlen - pos, p[element].balls, p[element].balls_size);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __balls_t_decode_array_cleanup(balls_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_decode_array_cleanup(&(p[element].info), 1);
 
        __int32_t_decode_array_cleanup(&(p[element].balls_size), 1);
 
        __ball_t_decode_array_cleanup(p[element].balls, p[element].balls_size);
        if (p[element].balls) free(p[element].balls);
 
    }
    return 0;
}
 
int balls_t_decode(const void *buf, int offset, int maxlen, balls_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __balls_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __balls_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int balls_t_decode_cleanup(balls_t *p)
{
    return __balls_t_decode_array_cleanup(p, 1);
}
 
int __balls_t_clone_array(const balls_t *p, balls_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_clone_array(&(p[element].info), &(q[element].info), 1);
 
        __int32_t_clone_array(&(p[element].balls_size), &(q[element].balls_size), 1);
 
        q[element].balls = (ball_t*) lcm_malloc(sizeof(ball_t) * q[element].balls_size);
        __ball_t_clone_array(p[element].balls, q[element].balls, p[element].balls_size);
 
    }
    return 0;
}
 
balls_t *balls_t_copy(const balls_t *p)
{
    balls_t *q = (balls_t*) malloc(sizeof(balls_t));
    __balls_t_clone_array(p, q, 1);
    return q;
}
 
void balls_t_destroy(balls_t *p)
{
    __balls_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int balls_t_publish(lcm_t *lc, const char *channel, const balls_t *p)
{
      int max_data_size = balls_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = balls_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _balls_t_subscription_t {
    balls_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void balls_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    balls_t p;
    memset(&p, 0, sizeof(balls_t));
    status = balls_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding balls_t!!!\n", status);
        return;
    }

    balls_t_subscription_t *h = (balls_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    balls_t_decode_cleanup (&p);
}

balls_t_subscription_t* balls_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    balls_t_handler_t f, void *userdata)
{
    balls_t_subscription_t *n = (balls_t_subscription_t*)
                       malloc(sizeof(balls_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 balls_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg balls_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int balls_t_unsubscribe(lcm_t *lcm, balls_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe balls_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

