/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _balls_t_h
#define _balls_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "info_t.h"
#include "ball_t.h"
typedef struct _balls_t balls_t;
struct _balls_t
{
    info_t     info;
    int32_t    balls_size;
    ball_t     *balls;
};
 
balls_t   *balls_t_copy(const balls_t *p);
void balls_t_destroy(balls_t *p);

typedef struct _balls_t_subscription_t balls_t_subscription_t;
typedef void(*balls_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const balls_t *msg, void *user);

int balls_t_publish(lcm_t *lcm, const char *channel, const balls_t *p);
balls_t_subscription_t* balls_t_subscribe(lcm_t *lcm, const char *channel, balls_t_handler_t f, void *userdata);
int balls_t_unsubscribe(lcm_t *lcm, balls_t_subscription_t* hid);

int  balls_t_encode(void *buf, int offset, int maxlen, const balls_t *p);
int  balls_t_decode(const void *buf, int offset, int maxlen, balls_t *p);
int  balls_t_decode_cleanup(balls_t *p);
int  balls_t_encoded_size(const balls_t *p);

// LCM support functions. Users should not call these
int64_t __balls_t_get_hash(void);
int64_t __balls_t_hash_recursive(const __lcm_hash_ptr *p);
int     __balls_t_encode_array(void *buf, int offset, int maxlen, const balls_t *p, int elements);
int     __balls_t_decode_array(const void *buf, int offset, int maxlen, balls_t *p, int elements);
int     __balls_t_decode_array_cleanup(balls_t *p, int elements);
int     __balls_t_encoded_array_size(const balls_t *p, int elements);
int     __balls_t_clone_array(const balls_t *p, balls_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
