/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _ball_t_h
#define _ball_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define BALL_T_RED 0
#define BALL_T_BLUE 1

typedef struct _ball_t ball_t;
struct _ball_t
{
    double     position[2];
    int32_t    colour;
};
 
ball_t   *ball_t_copy(const ball_t *p);
void ball_t_destroy(ball_t *p);

typedef struct _ball_t_subscription_t ball_t_subscription_t;
typedef void(*ball_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const ball_t *msg, void *user);

int ball_t_publish(lcm_t *lcm, const char *channel, const ball_t *p);
ball_t_subscription_t* ball_t_subscribe(lcm_t *lcm, const char *channel, ball_t_handler_t f, void *userdata);
int ball_t_unsubscribe(lcm_t *lcm, ball_t_subscription_t* hid);

int  ball_t_encode(void *buf, int offset, int maxlen, const ball_t *p);
int  ball_t_decode(const void *buf, int offset, int maxlen, ball_t *p);
int  ball_t_decode_cleanup(ball_t *p);
int  ball_t_encoded_size(const ball_t *p);

// LCM support functions. Users should not call these
int64_t __ball_t_get_hash(void);
int64_t __ball_t_hash_recursive(const __lcm_hash_ptr *p);
int     __ball_t_encode_array(void *buf, int offset, int maxlen, const ball_t *p, int elements);
int     __ball_t_decode_array(const void *buf, int offset, int maxlen, ball_t *p, int elements);
int     __ball_t_decode_array_cleanup(ball_t *p, int elements);
int     __ball_t_encoded_array_size(const ball_t *p, int elements);
int     __ball_t_clone_array(const ball_t *p, ball_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
