/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "cam_t.h"

static int __cam_t_hash_computed;
static int64_t __cam_t_hash;
 
int64_t __cam_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __cam_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__cam_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x373999221c1c74ccLL
         + __info_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __cam_t_get_hash(void)
{
    if (!__cam_t_hash_computed) {
        __cam_t_hash = __cam_t_hash_recursive(NULL);
        __cam_t_hash_computed = 1;
    }
 
    return __cam_t_hash;
}
 
int __cam_t_encode_array(void *buf, int offset, int maxlen, const cam_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].hasVision), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].p0, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].p1, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].p2, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].p3, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int cam_t_encode(void *buf, int offset, int maxlen, const cam_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __cam_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __cam_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __cam_t_encoded_array_size(const cam_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __info_t_encoded_array_size(&(p[element].info), 1);
 
        size += __int8_t_encoded_array_size(&(p[element].hasVision), 1);
 
        size += __double_encoded_array_size(p[element].p0, 2);
 
        size += __double_encoded_array_size(p[element].p1, 2);
 
        size += __double_encoded_array_size(p[element].p2, 2);
 
        size += __double_encoded_array_size(p[element].p3, 2);
 
    }
    return size;
}
 
int cam_t_encoded_size(const cam_t *p)
{
    return 8 + __cam_t_encoded_array_size(p, 1);
}
 
int __cam_t_decode_array(const void *buf, int offset, int maxlen, cam_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].hasVision), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].p0, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].p1, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].p2, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].p3, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __cam_t_decode_array_cleanup(cam_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_decode_array_cleanup(&(p[element].info), 1);
 
        __int8_t_decode_array_cleanup(&(p[element].hasVision), 1);
 
        __double_decode_array_cleanup(p[element].p0, 2);
 
        __double_decode_array_cleanup(p[element].p1, 2);
 
        __double_decode_array_cleanup(p[element].p2, 2);
 
        __double_decode_array_cleanup(p[element].p3, 2);
 
    }
    return 0;
}
 
int cam_t_decode(const void *buf, int offset, int maxlen, cam_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __cam_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __cam_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int cam_t_decode_cleanup(cam_t *p)
{
    return __cam_t_decode_array_cleanup(p, 1);
}
 
int __cam_t_clone_array(const cam_t *p, cam_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_clone_array(&(p[element].info), &(q[element].info), 1);
 
        __int8_t_clone_array(&(p[element].hasVision), &(q[element].hasVision), 1);
 
        __double_clone_array(p[element].p0, q[element].p0, 2);
 
        __double_clone_array(p[element].p1, q[element].p1, 2);
 
        __double_clone_array(p[element].p2, q[element].p2, 2);
 
        __double_clone_array(p[element].p3, q[element].p3, 2);
 
    }
    return 0;
}
 
cam_t *cam_t_copy(const cam_t *p)
{
    cam_t *q = (cam_t*) malloc(sizeof(cam_t));
    __cam_t_clone_array(p, q, 1);
    return q;
}
 
void cam_t_destroy(cam_t *p)
{
    __cam_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int cam_t_publish(lcm_t *lc, const char *channel, const cam_t *p)
{
      int max_data_size = cam_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = cam_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _cam_t_subscription_t {
    cam_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void cam_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    cam_t p;
    memset(&p, 0, sizeof(cam_t));
    status = cam_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding cam_t!!!\n", status);
        return;
    }

    cam_t_subscription_t *h = (cam_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    cam_t_decode_cleanup (&p);
}

cam_t_subscription_t* cam_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    cam_t_handler_t f, void *userdata)
{
    cam_t_subscription_t *n = (cam_t_subscription_t*)
                       malloc(sizeof(cam_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 cam_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg cam_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int cam_t_unsubscribe(lcm_t *lcm, cam_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe cam_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

