/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "cube_t.h"

static int __cube_t_hash_computed;
static int64_t __cube_t_hash;
 
int64_t __cube_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __cube_t_get_hash)
            return 0;
 
    const __lcm_hash_ptr cp = { p, (void*)__cube_t_get_hash };
    (void) cp;
 
    int64_t hash = 0x185e71596dcf459aLL
         + __info_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;
 
    return (hash<<1) + ((hash>>63)&1);
}
 
int64_t __cube_t_get_hash(void)
{
    if (!__cube_t_hash_computed) {
        __cube_t_hash = __cube_t_hash_recursive(NULL);
        __cube_t_hash_computed = 1;
    }
 
    return __cube_t_hash;
}
 
int __cube_t_encode_array(void *buf, int offset, int maxlen, const cube_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].orientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int cube_t_encode(void *buf, int offset, int maxlen, const cube_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __cube_t_get_hash();
 
    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    thislen = __cube_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int __cube_t_encoded_array_size(const cube_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {
 
        size += __info_t_encoded_array_size(&(p[element].info), 1);
 
        size += __string_encoded_array_size(&(p[element].id), 1);
 
        size += __double_encoded_array_size(p[element].position, 2);
 
        size += __double_encoded_array_size(&(p[element].orientation), 1);
 
    }
    return size;
}
 
int cube_t_encoded_size(const cube_t *p)
{
    return 8 + __cube_t_encoded_array_size(p, 1);
}
 
int __cube_t_decode_array(const void *buf, int offset, int maxlen, cube_t *p, int elements)
{
    int pos = 0, thislen, element;
 
    for (element = 0; element < elements; element++) {
 
        thislen = __info_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].info), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].id), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, p[element].position, 2);
        if (thislen < 0) return thislen; else pos += thislen;
 
        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].orientation), 1);
        if (thislen < 0) return thislen; else pos += thislen;
 
    }
    return pos;
}
 
int __cube_t_decode_array_cleanup(cube_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_decode_array_cleanup(&(p[element].info), 1);
 
        __string_decode_array_cleanup(&(p[element].id), 1);
 
        __double_decode_array_cleanup(p[element].position, 2);
 
        __double_decode_array_cleanup(&(p[element].orientation), 1);
 
    }
    return 0;
}
 
int cube_t_decode(const void *buf, int offset, int maxlen, cube_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __cube_t_get_hash();
 
    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;
 
    thislen = __cube_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;
 
    return pos;
}
 
int cube_t_decode_cleanup(cube_t *p)
{
    return __cube_t_decode_array_cleanup(p, 1);
}
 
int __cube_t_clone_array(const cube_t *p, cube_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {
 
        __info_t_clone_array(&(p[element].info), &(q[element].info), 1);
 
        __string_clone_array(&(p[element].id), &(q[element].id), 1);
 
        __double_clone_array(p[element].position, q[element].position, 2);
 
        __double_clone_array(&(p[element].orientation), &(q[element].orientation), 1);
 
    }
    return 0;
}
 
cube_t *cube_t_copy(const cube_t *p)
{
    cube_t *q = (cube_t*) malloc(sizeof(cube_t));
    __cube_t_clone_array(p, q, 1);
    return q;
}
 
void cube_t_destroy(cube_t *p)
{
    __cube_t_decode_array_cleanup(p, 1);
    free(p);
}
 
int cube_t_publish(lcm_t *lc, const char *channel, const cube_t *p)
{
      int max_data_size = cube_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = cube_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _cube_t_subscription_t {
    cube_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void cube_t_handler_stub (const lcm_recv_buf_t *rbuf, 
                            const char *channel, void *userdata)
{
    int status;
    cube_t p;
    memset(&p, 0, sizeof(cube_t));
    status = cube_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding cube_t!!!\n", status);
        return;
    }

    cube_t_subscription_t *h = (cube_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    cube_t_decode_cleanup (&p);
}

cube_t_subscription_t* cube_t_subscribe (lcm_t *lcm, 
                    const char *channel, 
                    cube_t_handler_t f, void *userdata)
{
    cube_t_subscription_t *n = (cube_t_subscription_t*)
                       malloc(sizeof(cube_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel, 
                                 cube_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg cube_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int cube_t_unsubscribe(lcm_t *lcm, cube_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr, 
           "couldn't unsubscribe cube_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

