/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _cube_t_h
#define _cube_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "info_t.h"
typedef struct _cube_t cube_t;
struct _cube_t
{
    info_t     info;
    char*      id;
    double     position[2];
    double     orientation;
};
 
cube_t   *cube_t_copy(const cube_t *p);
void cube_t_destroy(cube_t *p);

typedef struct _cube_t_subscription_t cube_t_subscription_t;
typedef void(*cube_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const cube_t *msg, void *user);

int cube_t_publish(lcm_t *lcm, const char *channel, const cube_t *p);
cube_t_subscription_t* cube_t_subscribe(lcm_t *lcm, const char *channel, cube_t_handler_t f, void *userdata);
int cube_t_unsubscribe(lcm_t *lcm, cube_t_subscription_t* hid);

int  cube_t_encode(void *buf, int offset, int maxlen, const cube_t *p);
int  cube_t_decode(const void *buf, int offset, int maxlen, cube_t *p);
int  cube_t_decode_cleanup(cube_t *p);
int  cube_t_encoded_size(const cube_t *p);

// LCM support functions. Users should not call these
int64_t __cube_t_get_hash(void);
int64_t __cube_t_hash_recursive(const __lcm_hash_ptr *p);
int     __cube_t_encode_array(void *buf, int offset, int maxlen, const cube_t *p, int elements);
int     __cube_t_decode_array(const void *buf, int offset, int maxlen, cube_t *p, int elements);
int     __cube_t_decode_array_cleanup(cube_t *p, int elements);
int     __cube_t_encoded_array_size(const cube_t *p, int elements);
int     __cube_t_clone_array(const cube_t *p, cube_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
