/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _info_t_h
#define _info_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _info_t info_t;
struct _info_t
{
    int64_t    timestamp;
    char*      source;
};
 
info_t   *info_t_copy(const info_t *p);
void info_t_destroy(info_t *p);

typedef struct _info_t_subscription_t info_t_subscription_t;
typedef void(*info_t_handler_t)(const lcm_recv_buf_t *rbuf, 
             const char *channel, const info_t *msg, void *user);

int info_t_publish(lcm_t *lcm, const char *channel, const info_t *p);
info_t_subscription_t* info_t_subscribe(lcm_t *lcm, const char *channel, info_t_handler_t f, void *userdata);
int info_t_unsubscribe(lcm_t *lcm, info_t_subscription_t* hid);

int  info_t_encode(void *buf, int offset, int maxlen, const info_t *p);
int  info_t_decode(const void *buf, int offset, int maxlen, info_t *p);
int  info_t_decode_cleanup(info_t *p);
int  info_t_encoded_size(const info_t *p);

// LCM support functions. Users should not call these
int64_t __info_t_get_hash(void);
int64_t __info_t_hash_recursive(const __lcm_hash_ptr *p);
int     __info_t_encode_array(void *buf, int offset, int maxlen, const info_t *p, int elements);
int     __info_t_decode_array(const void *buf, int offset, int maxlen, info_t *p, int elements);
int     __info_t_decode_array_cleanup(info_t *p, int elements);
int     __info_t_encoded_array_size(const info_t *p, int elements);
int     __info_t_clone_array(const info_t *p, info_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
